akka/akka-quickstart-java.g8

src/main/g8/default.properties

g8 is reading default.properties file from src/main/g8/default.properties
There was one in project/ but that one is probably for example code service (not completely sure)

Add description and parameters for g8

---

docs/src/main/paradox/communicate-with-actors.md

Resolves https://github.com/akka/akka-quickstart-java.g8/issues/16

=doc #16 talk about tell, since Java API

---

src/main/g8/build.gradle

Gradle build should include maven central #14

---

README.md
docs/src/main/paradox/index.md

(especially important since redirects are currently broken,
https://github.com/lightbend/techhub/issues/145)

Fix links to developer.lightbend.com

---

.gitignore
src/main/g8/pom.xml
src/main/g8/src/main/java/com/lightbend/akka/sample/AkkaQuickstart.java
src/main/g8/src/main/java/com/lightbend/akka/sample/Printer.java
src/main/g8/src/test/java/com/lightbend/akka/sample/AkkaQuickstartTest.java

- Removed unused imports & organised imports based on standards
- Marked test libs as test scope in pom
- Added git-ignore

Cleanup changes (import, mvn test, git)

---

src/main/g8/default.properties
src/main/g8/src/main/resources/logback.xml

Also Scala to 2.13
Messed up previous PR, so redoing to get it right.

Update Akka 2.6.0

---

src/main/g8/build.sbt
src/main/g8/default.properties

Scala 2.13 hardcode instead of user choice

---

src/main/g8/build.gradle
src/main/g8/pom.xml

Missed this when hardcoding Scala 2.13 yesterday

Scala version for gradle and maven

---

docs/src/main/paradox/create-actors.md
docs/src/main/paradox/define-actors.md
src/main/g8/src/main/java/com/lightbend/akka/sample/AkkaQuickstart.java
src/main/g8/src/main/java/com/lightbend/akka/sample/GreeterMain.java

to keep in sync with sample in Akka docs, see https://github.com/akka/akka/pull/28469

Rename Start message to SayHello

---

src/main/g8/default.properties

Derive version from _2.11 resource to find 2.5.x

---

docs/src/main/paradox/running-the-application.md

Noted confusion during workshop about this

Small clarification that the application doesn't stop on its own

---

.gitignore
docs/src/main/paradox/communicate-with-actors.md
docs/src/main/paradox/create-actors.md
docs/src/main/paradox/define-actors.md
docs/src/main/paradox/full-example.md
docs/src/main/paradox/intellij-idea.md
docs/src/main/paradox/main-class.md
docs/src/main/paradox/testing-actors.md
src/main/g8/build.gradle
src/main/g8/default.properties
src/main/g8/pom.xml
src/main/g8/src/main/java/$package$/AkkaQuickstart.java
src/main/g8/src/main/java/$package$/Greeter.java
src/main/g8/src/main/java/$package$/GreeterBot.java
src/main/g8/src/main/java/$package$/GreeterMain.java
src/main/g8/src/test/java/$package$/AkkaQuickstartTest.java

... and don't default to com.lightbend
Aligns with the scala quickstart and the docs

Use a user specified package 

---

docs/src/main/paradox/index.md

Hi,
Just wanted to submit a few doc edits to the Quickstart guide.
In the console output for Gradle & Maven on that page, the type of the Bot should be GreeterBot and not HelloWorldBot.
Also on the same page, in the **What Hello World does** section, the first bullet point should be Greeter and not Greet.
Hope this helps.

Fixed minor issues in index.md

---

docs/src/main/paradox/running-the-application.md

Related to [this](https://gitter.im/akka/akka?at=5e8c822c9316f34b8d870ed3) gitter comment.

Adds note wrt artifact suffix and scalaVersion

---

docs/src/main/paradox/running-the-application.md

Currently deployed content in https://developer.lightbend.com/guides/akka-quickstart-java/running-the-application.html is defaced:

Syntax errors

---

src/main/g8/build.gradle
src/main/g8/build.sbt

Bump junit

---

docs/src/main/paradox/communicate-with-actors.md

See also akka/akka-quickstart-scala.g8#59

Clarify acknowledgement of receipt of greeting

---

docs/src/main/paradox/create-actors.md

See also akka/akka-quickstart-scala.g8#58

Clarify guardian actor of the ActorSystem

---

.travis.yml

To avoid the jabba install page load issues.

CI JDK management from akka-persistence-cassandra

---

docs/src/main/paradox/index.md

fix: remove link to project starter

---

docs/src/main/paradox/define-actors.md

Just a minor spelling correction

Fix minor spelling error

---

build.sbt
docs/build.sbt
project/build.properties
src/main/g8/pom.xml

A few bumps, nothing really important.

chore: Bump some quickstart dependency versions

---

project/build.properties
project/giter8.sbt
project/paradox.sbt
src/main/g8/build.sbt

As the other repos are unstable/going away: https://contributors.scala-lang.org/t/roadmap-for-the-sbt-community-repository/6195

build: Bump plugins to only download from maven central

---

src/main/g8/default.properties

bump: Akka 2.9.2
